disabled_rules:
  - trailing_comma
opt_in_rules:
  - closure_spacing
  - empty_count
line_length:
  warning: 140
  error: 200
identifier_name:
  min_length:
    warning: 2
excluded:
  - OxygenieTests
